CREATE TABLE IF NOT EXISTS POSITION_EVENT (
   ID_EVENT VARCHAR(50) PRIMARY KEY,
   ID_OWNER VARCHAR(50) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   EVENT_TIMESTAMP TIMESTAMP NOT NULL,
   LATITUDE DOUBLE PRECISION NOT NULL,
   LONGITUDE DOUBLE PRECISION NOT NULL
);
