version: '3.1'
services:
  app:
    image: ilecreurer/drools-sample2/postgresql:1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/droolssample2db
      - SPRING_DATASOURCE_USERNAME=postgres_u
      - SPRING_DATASOURCE_PASSWORD=postgres_p
    depends_on:
      - dbpostgresql

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_p
      - POSTGRES_USER=postgres_u
      - POSTGRES_DB=droolssample2db