apiVersion: apps/v1
kind: Deployment
metadata:
  name: droolssample2
spec:
  selector:
    matchLabels:
      app: droolssample2
  template:
    metadata:
      labels:
        app: droolssample2
    spec:
      containers:
      - name: droolssample2
        image: ilecreurer/drools-sample2/postgresql:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://dbpostgresql:5432/droolssample2db
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres_u
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres_p
        - name: AREA_MINLATITUDE
          value: "40"
        - name: AREA_MAXLATITUDE
          value: "90"
        - name: AREA_MINLONGITUDE
          value: "-100"
        - name: AREA_MAXLONGITUDE
          value: "-50"